<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jinhyo Lee">
<meta name="dcterms.date" content="2025-02-26">

<title>Project1 – Jinhyo Lee</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d801ec56ef41a5df713aa3b4cba1a403.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Jinhyo Lee</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Projects.html"> 
<span class="menu-text">Project</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary:</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction:</a></li>
  <li><a href="#finding-the-final-model" id="toc-finding-the-final-model" class="nav-link" data-scroll-target="#finding-the-final-model">Finding the Final model:</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion:</a>
  <ul class="collapse">
  <li><a href="#intercept-the-base-price-is-about-1874.25." id="toc-intercept-the-base-price-is-about-1874.25." class="nav-link" data-scroll-target="#intercept-the-base-price-is-about-1874.25.">Intercept: The base price is about 1874.25.</a></li>
  <li><a href="#resolution-for-every-1-unit-increase-in-resolution-the-price-decreases-by-approximately-100.48p-0.05." id="toc-resolution-for-every-1-unit-increase-in-resolution-the-price-decreases-by-approximately-100.48p-0.05." class="nav-link" data-scroll-target="#resolution-for-every-1-unit-increase-in-resolution-the-price-decreases-by-approximately-100.48p-0.05.">resolution: for every 1 unit increase in resolution, the price decreases by approximately 100.48(p &lt; 0.05).</a></li>
  <li><a href="#ppi-for-every-1-unit-increase-in-pixel-density-the-price-increases-by-approximately-1.11p-0.05." id="toc-ppi-for-every-1-unit-increase-in-pixel-density-the-price-increases-by-approximately-1.11p-0.05." class="nav-link" data-scroll-target="#ppi-for-every-1-unit-increase-in-pixel-density-the-price-increases-by-approximately-1.11p-0.05.">ppi: for every 1 unit increase in pixel density, the price increases by approximately 1.11(p &lt; 0.05).</a></li>
  <li><a href="#cpu.core-for-every-1-unit-increase-in-cpu-cores-the-price-increases-by-approximately-63.94-p-0.05." id="toc-cpu.core-for-every-1-unit-increase-in-cpu-cores-the-price-increases-by-approximately-63.94-p-0.05." class="nav-link" data-scroll-target="#cpu.core-for-every-1-unit-increase-in-cpu-cores-the-price-increases-by-approximately-63.94-p-0.05.">cpu.core: for every 1 unit increase in CPU cores, the price increases by approximately 63.94 (p &lt; 0.05).</a></li>
  <li><a href="#cpu.freq-for-every-1-unit-increase-in-cpu-frequency-the-price-increases-by-approximately-135.55-p-0.05." id="toc-cpu.freq-for-every-1-unit-increase-in-cpu-frequency-the-price-increases-by-approximately-135.55-p-0.05." class="nav-link" data-scroll-target="#cpu.freq-for-every-1-unit-increase-in-cpu-frequency-the-price-increases-by-approximately-135.55-p-0.05.">cpu.freq: For every 1 unit increase in CPU frequency, the price increases by approximately 135.55 (p &lt; 0.05).</a></li>
  <li><a href="#internal.mem-for-every-1-unit-increase-in-internal-memory-the-price-increases-by-approximately-5.40-p-0.05." id="toc-internal.mem-for-every-1-unit-increase-in-internal-memory-the-price-increases-by-approximately-5.40-p-0.05." class="nav-link" data-scroll-target="#internal.mem-for-every-1-unit-increase-in-internal-memory-the-price-increases-by-approximately-5.40-p-0.05.">internal.mem: for every 1 unit increase in internal memory, the price increases by approximately 5.40 (p &lt; 0.05).</a></li>
  <li><a href="#ram-for-every-1-unit-increase-in-ram-the-price-increases-by-approximately-114.68-p-0.05." id="toc-ram-for-every-1-unit-increase-in-ram-the-price-increases-by-approximately-114.68-p-0.05." class="nav-link" data-scroll-target="#ram-for-every-1-unit-increase-in-ram-the-price-increases-by-approximately-114.68-p-0.05.">ram: For every 1 unit increase in RAM, the price increases by approximately 114.68 (p &lt; 0.05).</a></li>
  <li><a href="#battery-for-every-1-unit-increase-in-battery-capacity-the-price-increases-by-approximately-0.11-p-0.05." id="toc-battery-for-every-1-unit-increase-in-battery-capacity-the-price-increases-by-approximately-0.11-p-0.05." class="nav-link" data-scroll-target="#battery-for-every-1-unit-increase-in-battery-capacity-the-price-increases-by-approximately-0.11-p-0.05.">battery: for every 1 unit increase in battery capacity, the price increases by approximately 0.11 (p &lt; 0.05).</a></li>
  <li><a href="#thickness-for-every-1-unit-increase-in-thickness-the-price-decreases-by-approximately-82.14-p-0.05." id="toc-thickness-for-every-1-unit-increase-in-thickness-the-price-decreases-by-approximately-82.14-p-0.05." class="nav-link" data-scroll-target="#thickness-for-every-1-unit-increase-in-thickness-the-price-decreases-by-approximately-82.14-p-0.05.">thickness: for every 1 unit increase in thickness, the price decreases by approximately 82.14 (p &lt; 0.05).</a></li>
  </ul></li>
  <li><a href="#diagnostics-model-assumption-for-final-model" id="toc-diagnostics-model-assumption-for-final-model" class="nav-link" data-scroll-target="#diagnostics-model-assumption-for-final-model">Diagnostics model assumption for final model</a></li>
  <li><a href="#linearity" id="toc-linearity" class="nav-link" data-scroll-target="#linearity">Linearity:</a></li>
  <li><a href="#normality" id="toc-normality" class="nav-link" data-scroll-target="#normality">Normality :</a></li>
  <li><a href="#homoscedasticity" id="toc-homoscedasticity" class="nav-link" data-scroll-target="#homoscedasticity">Homoscedasticity:</a></li>
  <li><a href="#outliers-or-possible-influential-points" id="toc-outliers-or-possible-influential-points" class="nav-link" data-scroll-target="#outliers-or-possible-influential-points">outliers or (possible) influential points:</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jinhyo Lee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 26, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary:</h2>
<p>The fact that the R-squared value is 0.9516 indicates that this model explains most of the price volatility of the Cellphone well. The adjusted R-squared is high at 0.949, indicating that the model explains the data well even considering the number of independent variables. The F-statistics confirm that the model is statistically significant and provide strong evidence that the selected independent variables have a significant influence on the price of the Cellphone.</p>
<p>Looking at the contribution of each variable, the resolution was found to have a negative effect on the price, while pixel density, number of CPU cores, CPU frequency, internal memory, RAM, and battery capacity seem to contribute to the increase of the price. Thickness was analyzed to have a negative effect on the price as well as the resolution.</p>
<p>Considering the overall model fit and flexibility of the assumption review results, it can be concluded that the model captures the key factors in pricing. This analysis will provide useful insights into future Cellphone pricing strategies.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.3.3</code></pre>
</div>
</div>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction:</h2>
<p>Data set: Mobile price depends on various factors such as resolution, weight, Phone Pixel Density(ppi), RAM, battery and CPU core and frequency, internal memory, camera of cellphone, thickness. Dataset is numeric value. In this dataset, we want to estimate the price of mobile phones using the above features. I set up the Price of Cellphone as response ”Y”. Other things (weight, ppi, RAM, battery..) are predictors for predicting response Y beacuse technical characteristics were judged to be important for Cellphone price prediction, variables such as resolution, CPU core, and internal memory were selected. I set the hypothesis, H0: b1 = b2 = … = bp = 0, Ha: At least one b1 is not 0. I f H0 reject, we say this result indicated that at least one predictor contributes significantly to accounting for the variability of the response variable (cell phone price).Now we check table of summary about the data.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Feature</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">X1st.Qu.</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">X3rd.Qu.</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Price</td>
<td style="text-align: right;">614.0</td>
<td style="text-align: right;">1734.0</td>
<td style="text-align: right;">2258.00</td>
<td style="text-align: right;">2215.596273</td>
<td style="text-align: right;">2744.000</td>
<td style="text-align: right;">4361.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">weight</td>
<td style="text-align: right;">66.0</td>
<td style="text-align: right;">134.1</td>
<td style="text-align: right;">153.00</td>
<td style="text-align: right;">170.426087</td>
<td style="text-align: right;">170.000</td>
<td style="text-align: right;">753.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">resoloution</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">5.15</td>
<td style="text-align: right;">5.209938</td>
<td style="text-align: right;">5.500</td>
<td style="text-align: right;">12.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">ppi</td>
<td style="text-align: right;">121.0</td>
<td style="text-align: right;">233.0</td>
<td style="text-align: right;">294.00</td>
<td style="text-align: right;">335.055901</td>
<td style="text-align: right;">428.000</td>
<td style="text-align: right;">806.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cpu.core</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">4.857143</td>
<td style="text-align: right;">8.000</td>
<td style="text-align: right;">8.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">cpu.freq</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">1.40</td>
<td style="text-align: right;">1.502832</td>
<td style="text-align: right;">1.875</td>
<td style="text-align: right;">2.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">internal.mem</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">8.0</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">24.501714</td>
<td style="text-align: right;">32.000</td>
<td style="text-align: right;">128.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ram</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">2.204994</td>
<td style="text-align: right;">3.000</td>
<td style="text-align: right;">6.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RearCam</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">10.378261</td>
<td style="text-align: right;">16.000</td>
<td style="text-align: right;">23.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Front_Cam</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">4.503106</td>
<td style="text-align: right;">8.000</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">battery</td>
<td style="text-align: right;">800.0</td>
<td style="text-align: right;">2040.0</td>
<td style="text-align: right;">2800.00</td>
<td style="text-align: right;">2842.111801</td>
<td style="text-align: right;">3240.000</td>
<td style="text-align: right;">9500.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">thickness</td>
<td style="text-align: right;">5.1</td>
<td style="text-align: right;">7.6</td>
<td style="text-align: right;">8.40</td>
<td style="text-align: right;">8.921739</td>
<td style="text-align: right;">9.800</td>
<td style="text-align: right;">18.5</td>
</tr>
</tbody>
</table>
</section>
<section id="finding-the-final-model" class="level2">
<h2 class="anchored" data-anchor-id="finding-the-final-model">Finding the Final model:</h2>
<p>Now, I set up the first multiple linear regression model.The first model is full model, including response(Price) and all predictors.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ ., data = st)

Residuals:
    Min      1Q  Median      3Q     Max 
-390.49 -115.61    7.34  122.08  463.01 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1739.98213  217.91728   7.985 3.51e-13 ***
weight         -0.68753    0.68257  -1.007 0.315439    
resoloution   -67.40376   42.32976  -1.592 0.113426    
ppi             1.05375    0.21771   4.840 3.21e-06 ***
cpu.core       55.18927    9.83031   5.614 9.38e-08 ***
cpu.freq      126.24294   44.85564   2.814 0.005547 ** 
internal.mem    5.30216    1.13663   4.665 6.82e-06 ***
ram           101.31322   25.52192   3.970 0.000112 ***
RearCam         2.75395    4.21033   0.654 0.514060    
Front_Cam       5.80191    4.98359   1.164 0.246202    
battery         0.13864    0.02999   4.624 8.12e-06 ***
thickness     -74.97856   12.57601  -5.962 1.73e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 172.8 on 149 degrees of freedom
Multiple R-squared:  0.9529,    Adjusted R-squared:  0.9494 
F-statistic:   274 on 11 and 149 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Now, I see the estimators, std.error and p-value. But some predictors of this first model has large p-value. So we should do model selection for finding our final model. I use the stepwise backward method to find fitting model. Now I get the reduced model.</p>
<p><span class="math inline">\(Y(Price)\)</span> = <span class="math inline">\(-101.9661\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_1(resolution)\)</span> + <span class="math inline">\(1.1304\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_2(ppi)\)</span>+ <span class="math inline">\(57.9263\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_3(cpu.core)\)</span><span class="math inline">\(+144.4653\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_4(cpu.freq)\)</span> + <span class="math inline">\(5.2046\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_5(internal.mem)\)</span> +<span class="math inline">\(104.1362\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_6(ram)\)</span>+ <span class="math inline">\(7.4358\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_7(Front_Cam)\)</span> +<span class="math inline">\(0.1205\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_8(battery)\)</span>-<span class="math inline">\(81.5036\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_9(thickness)\)</span></p>
<p>We check the p-value and estimates about predictors. Through the p-value, I can confirm that most predictors are statistically significant(p-value &lt; 0.05). However, only Frot_Cam(P-value is 0.123064) is not statistically significant here, the p-value is over 0.05.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ resoloution + ppi + cpu.core + cpu.freq + 
    internal.mem + ram + Front_Cam + battery + thickness, data = st)

Residuals:
    Min      1Q  Median      3Q     Max 
-375.43 -122.63   -0.29  113.32  474.95 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1863.8122   171.2672  10.882  &lt; 2e-16 ***
resoloution  -101.9661    22.8849  -4.456 1.62e-05 ***
ppi             1.1304     0.1918   5.893 2.38e-08 ***
cpu.core       57.9263     9.5919   6.039 1.15e-08 ***
cpu.freq      144.4653    41.7281   3.462 0.000697 ***
internal.mem    5.2046     1.1109   4.685 6.20e-06 ***
ram           104.1362    25.1621   4.139 5.79e-05 ***
Front_Cam       7.4358     4.7951   1.551 0.123064    
battery         0.1205     0.0253   4.761 4.47e-06 ***
thickness     -81.5036    10.7637  -7.572 3.39e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 172.7 on 151 degrees of freedom
Multiple R-squared:  0.9523,    Adjusted R-squared:  0.9495 
F-statistic: 335.2 on 9 and 151 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>I know from the p-value of t-test that Front_cam is not statistically significant, so I check if it has multicollinearity. If it has multicollinearity, the p-value is not a reliable result, so you can leave the predictor as it is, but if it is not, I will remove the predictor because I can trust the result of the p-value of t-test. Whether it has multicollinearity will be confirmed through a VIF test, and if the value of the VIF has a value of 5 or more, it is judged to have multicollinearity.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> resoloution          ppi     cpu.core     cpu.freq internal.mem          ram 
    6.409048     3.589976     2.949752     3.362114     5.496070     8.806853 
   Front_Cam      battery    thickness 
    2.326786     6.419613     2.989462 </code></pre>
</div>
</div>
<p>I don’t think the p-value for t-test is incorrectly formed because the VIF value of Front_cam does not exceed 5. Therefore, Front_cam has been confirmed to be not statistically significant, so it is removed from the final linear model. Finally, I find the final linear regression model.</p>
<p><span class="math inline">\(Y(Price)\)</span> = <span class="math inline">\(-101.9661\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_1(resolution)\)</span> + <span class="math inline">\(1.1304\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_2(ppi)\)</span>+ <span class="math inline">\(57.9263\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_3(cpu.core)\)</span><span class="math inline">\(+144.4653\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_4(cpu.freq)\)</span> + <span class="math inline">\(5.2046\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_5(internal.mem)\)</span> +<span class="math inline">\(104.1362\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_6(ram)\)</span> +<span class="math inline">\(0.1205\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_8(battery)\)</span>-<span class="math inline">\(81.5036\)</span><span class="math inline">\(\times\)</span><span class="math inline">\(x_9(thickness)\)</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ resoloution + ppi + cpu.core + cpu.freq + 
    internal.mem + ram + battery + thickness, data = st)

Residuals:
    Min      1Q  Median      3Q     Max 
-383.65 -134.31    7.76  126.88  453.68 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1874.24893  171.92389  10.902  &lt; 2e-16 ***
resoloution  -100.47709   22.97017  -4.374 2.25e-05 ***
ppi             1.11339    0.19238   5.787 3.96e-08 ***
cpu.core       63.93728    8.81421   7.254 1.93e-11 ***
cpu.freq      135.54582   41.52029   3.265  0.00135 ** 
internal.mem    5.40076    1.10877   4.871 2.76e-06 ***
ram           114.67902   24.33785   4.712 5.50e-06 ***
battery         0.11441    0.02511   4.556 1.06e-05 ***
thickness     -82.14064   10.80541  -7.602 2.81e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 173.4 on 152 degrees of freedom
Multiple R-squared:  0.9516,    Adjusted R-squared:  0.949 
F-statistic: 373.3 on 8 and 152 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion:</h2>
<p>R-squared: 0.9516, which means the model can account for about 95.16% of the variationy of the data. The adjusted R-squared is 0.949, indicating that independent variables well describe the variation of Cellphone prices. F-statistics: 373.3 (p-value &lt; 2.2e-16), indicating that the model as a whole is statistically significant, meaning that the set of independent variables significantly contributes to predicting the dependent variable, price.</p>
<section id="intercept-the-base-price-is-about-1874.25." class="level3">
<h3 class="anchored" data-anchor-id="intercept-the-base-price-is-about-1874.25.">Intercept: The base price is about 1874.25.</h3>
</section>
<section id="resolution-for-every-1-unit-increase-in-resolution-the-price-decreases-by-approximately-100.48p-0.05." class="level3">
<h3 class="anchored" data-anchor-id="resolution-for-every-1-unit-increase-in-resolution-the-price-decreases-by-approximately-100.48p-0.05.">resolution: for every 1 unit increase in resolution, the price decreases by approximately 100.48(p &lt; 0.05).</h3>
</section>
<section id="ppi-for-every-1-unit-increase-in-pixel-density-the-price-increases-by-approximately-1.11p-0.05." class="level3">
<h3 class="anchored" data-anchor-id="ppi-for-every-1-unit-increase-in-pixel-density-the-price-increases-by-approximately-1.11p-0.05.">ppi: for every 1 unit increase in pixel density, the price increases by approximately 1.11(p &lt; 0.05).</h3>
</section>
<section id="cpu.core-for-every-1-unit-increase-in-cpu-cores-the-price-increases-by-approximately-63.94-p-0.05." class="level3">
<h3 class="anchored" data-anchor-id="cpu.core-for-every-1-unit-increase-in-cpu-cores-the-price-increases-by-approximately-63.94-p-0.05.">cpu.core: for every 1 unit increase in CPU cores, the price increases by approximately 63.94 (p &lt; 0.05).</h3>
</section>
<section id="cpu.freq-for-every-1-unit-increase-in-cpu-frequency-the-price-increases-by-approximately-135.55-p-0.05." class="level3">
<h3 class="anchored" data-anchor-id="cpu.freq-for-every-1-unit-increase-in-cpu-frequency-the-price-increases-by-approximately-135.55-p-0.05.">cpu.freq: For every 1 unit increase in CPU frequency, the price increases by approximately 135.55 (p &lt; 0.05).</h3>
</section>
<section id="internal.mem-for-every-1-unit-increase-in-internal-memory-the-price-increases-by-approximately-5.40-p-0.05." class="level3">
<h3 class="anchored" data-anchor-id="internal.mem-for-every-1-unit-increase-in-internal-memory-the-price-increases-by-approximately-5.40-p-0.05.">internal.mem: for every 1 unit increase in internal memory, the price increases by approximately 5.40 (p &lt; 0.05).</h3>
</section>
<section id="ram-for-every-1-unit-increase-in-ram-the-price-increases-by-approximately-114.68-p-0.05." class="level3">
<h3 class="anchored" data-anchor-id="ram-for-every-1-unit-increase-in-ram-the-price-increases-by-approximately-114.68-p-0.05.">ram: For every 1 unit increase in RAM, the price increases by approximately 114.68 (p &lt; 0.05).</h3>
</section>
<section id="battery-for-every-1-unit-increase-in-battery-capacity-the-price-increases-by-approximately-0.11-p-0.05." class="level3">
<h3 class="anchored" data-anchor-id="battery-for-every-1-unit-increase-in-battery-capacity-the-price-increases-by-approximately-0.11-p-0.05.">battery: for every 1 unit increase in battery capacity, the price increases by approximately 0.11 (p &lt; 0.05).</h3>
</section>
<section id="thickness-for-every-1-unit-increase-in-thickness-the-price-decreases-by-approximately-82.14-p-0.05." class="level3">
<h3 class="anchored" data-anchor-id="thickness-for-every-1-unit-increase-in-thickness-the-price-decreases-by-approximately-82.14-p-0.05.">thickness: for every 1 unit increase in thickness, the price decreases by approximately 82.14 (p &lt; 0.05).</h3>
<p>The model still maintains a high coefficient of determination after excluding the front camera variable and is good at predicting cellphone prices. In particular, the number of CPU cores, RAM capacity, and CPU frequency have been shown to have a significant impact on pricing. Overall, the analysis provides useful information for cellphone manufacturers to consider technical specifications that are important in pricing.</p>
<p>The hypothesis, H0: b1 = b2 = … = bp = 0, Ha: At least one b1 is not 0. This is mainly addressed by the F-test. The F- statistic and its corresponding p-value (&lt; 2.2e-16) strongly reject H0, indicating that at least one predictor contributes significantly to accounting for the variability of the response variable (cell phone price).</p>
</section>
</section>
<section id="diagnostics-model-assumption-for-final-model" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics-model-assumption-for-final-model">Diagnostics model assumption for final model</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project1_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="linearity" class="level2">
<h2 class="anchored" data-anchor-id="linearity">Linearity:</h2>
<p>To satisfy linearity, the mean of the residuals should be zero, and the variance should be constant, regardless of the value predicted. The graph(residuals vs fitted plot) above shows that the data has a red line meandering close to the horizontal line of zero. This is not perfect, but it satisfies some linearity.</p>
</section>
<section id="normality" class="level2">
<h2 class="anchored" data-anchor-id="normality">Normality :</h2>
<p>In Q-Q plot, the assumption of normality is used to verify that residuals follow a normal distribution. In the plots provided, most of the data points are arranged along the diagonal, but show some deviation from both ends. This indicates that the normality of residuals is not perfect, especially suggesting that there may be heavy tails or outliers.</p>
</section>
<section id="homoscedasticity" class="level2">
<h2 class="anchored" data-anchor-id="homoscedasticity">Homoscedasticity:</h2>
<p>It checks by looking at Standardized residuals vs X plot. For a residual to have equal variance, it must be patternlessly distributed around the mean zero. In the horizontal line of the standardized residual plot is close to zero, and the lot shows an upward trend where the variance of the residual seems to increase as the predicted value increases, but it is generally satisfactory.</p>
</section>
<section id="outliers-or-possible-influential-points" class="level2">
<h2 class="anchored" data-anchor-id="outliers-or-possible-influential-points">outliers or (possible) influential points:</h2>
<p>Residuals vs Leverage plot helps identify influential cases (outliers) that can significantly influence the model’s predictions. I am looking for points outside Cook’s distance line. There are several points in your plot that are outside of boundaries or close to boundaries. Some data points in this graph are highlighted (e.g.&nbsp;38, 168, 158), which means that those data points have relatively higher values of Cook’s D than others, and thus have a greater impact on the regression model.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project1_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>       StudRes        Hat      CookD
33   2.6965593 0.02028308 0.01606393
48   2.6965593 0.02028308 0.01606393
153  0.9032993 0.22673103 0.02661506
154  0.9032993 0.22673103 0.02661506
158 -2.1755217 0.12818250 0.07546589
160 -2.1755217 0.12818250 0.07546589</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>